<html>
<head>
<title>TestNG:  Default test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Default test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>59/34/0</td>
</tr><tr>
<td>Started on:</td><td>Fri Jul 22 15:48:06 EDT 2022</td>
</tr>
<tr><td>Total time:</td><td>35 seconds (35556 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to delete non existing record successfully", "Optional[Validate and Test Delete Request for Morbidity API with valid authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at MorbidityAPI.DeleteMorbidity.status_not_found_is_displayed_with_a_message_is_displayed(DeleteMorbidity.java:74)
	at ?.Status 404 Not Found is displayed with a Message &quot;Already Deleted OR wrong MorbidityName ,MorbidityTestId.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:20)
</pre></div><a href='#' onClick='toggleBox("stack-trace943228473", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace943228473'><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at MorbidityAPI.DeleteMorbidity.status_not_found_is_displayed_with_a_message_is_displayed(DeleteMorbidity.java:74)
	at ?.Status 404 Not Found is displayed with a Message &quot;Already Deleted OR wrong MorbidityName ,MorbidityTestId.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:20)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get records of User by User Type with invalid credentials", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td><div><pre>java.lang.AssertionError: expected [404] but found [401]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.GetUser_UserType.status_unauthorized_access_should_be_displayed(GetUser_UserType.java:125)
	at ?.Status 401 Unauthorized access should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/GetUser_UserType.feature:37)
</pre></div><a href='#' onClick='toggleBox("stack-trace739626708", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace739626708'><pre>java.lang.AssertionError: expected [404] but found [401]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.GetUser_UserType.status_unauthorized_access_should_be_displayed(GetUser_UserType.java:125)
	at ?.Status 401 Unauthorized access should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/GetUser_UserType.feature:37)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if existing record gets updated with same values", "Optional[Validate Put User Request for Dietician Users API]"</td>
<td><div><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_code_for_successful_update_should_be_displayed(PutUsers.java:127)
	at ?.status code 200 for successful update should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:13)
</pre></div><a href='#' onClick='toggleBox("stack-trace144817506", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace144817506'><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_code_for_successful_update_should_be_displayed(PutUsers.java:127)
	at ?.status code 200 for successful update should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:13)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is able to create a new user record", "Optional[Validate and Test POST request for Users API]"</td>
<td><div><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: Successfully Created.
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:119)
	at ?.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:10)
</pre></div><a href='#' onClick='toggleBox("stack-trace888225845", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace888225845'><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: Successfully Created.
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:119)
	at ?.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:10)
</pre></div></td>
<td>2</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Non-Vegetarian with invalid request query string", "Optional[Validate and Test Get Request for DieticianAPI with Non-Vegetarian]"</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetNonVegetarianSteps.status_Validation_Error_be_displayed(RecipeAPIGetNonVegetarianSteps.java:68)
	at ?.Status 400 Validation Error be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetNonVegetarian.feature:15)
</pre></div><a href='#' onClick='toggleBox("stack-trace415254661", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace415254661'><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetNonVegetarianSteps.status_Validation_Error_be_displayed(RecipeAPIGetNonVegetarianSteps.java:68)
	at ?.Status 400 Validation Error be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetNonVegetarian.feature:15)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets Internal Server error.", "Optional[Verify Get Request for Morbidity Name API.]"</td>
<td><div><pre>java.lang.AssertionError: expected [500] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidAPI_MorbidityNameStepDef.user_will_checks_for_ok_and(MorbidAPI_MorbidityNameStepDef.java:52)
	at ?.User will checks for 500  Ok and(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetMorbidityFeatures/Morbidity_MorbidityNameAPI.feature:34)
</pre></div><a href='#' onClick='toggleBox("stack-trace1530193853", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1530193853'><pre>java.lang.AssertionError: expected [500] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidAPI_MorbidityNameStepDef.user_will_checks_for_ok_and(MorbidAPI_MorbidityNameStepDef.java:52)
	at ?.User will checks for 500  Ok and(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetMorbidityFeatures/Morbidity_MorbidityNameAPI.feature:34)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if user record gets updated in case of incorrect or non existent id", "Optional[Validate Put User Request for Dietician Users API]"</td>
<td><div><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_user_id_not_found_should_be_displayed(PutUsers.java:194)
	at ?.Status 400 user id not found should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:25)
</pre></div><a href='#' onClick='toggleBox("stack-trace1268894895", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1268894895'><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_user_id_not_found_should_be_displayed(PutUsers.java:194)
	at ?.Status 400 user id not found should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:25)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that we are getting records of User by User Type - Dietician", "Optional[Validate Get User Request for Dietician Users API for User Type - Dietician]"</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at stepdefinitions.GetUser_Dietician.status_should_be_displayed_with_user_records_of_type_dietician(GetUser_Dietician.java:64)
	at ?.Status 200 should be displayed with user records of type Dietician(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/GetUser_Dietician.feature:7)
</pre></div><a href='#' onClick='toggleBox("stack-trace109243533", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace109243533'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at stepdefinitions.GetUser_Dietician.status_should_be_displayed_with_user_records_of_type_dietician(GetUser_Dietician.java:64)
	at ?.Status 200 should be displayed with user records of type Dietician(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/GetUser_Dietician.feature:7)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to add a new record successfully", "Optional[Validate and Test Post Request for Morbidity API with authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at MorbidityAPI.PostMorbidityAPI.status_bad_request_should_display_with_a_message_missing_items_or_invalid_entry_check_on_names(PostMorbidityAPI.java:160)
	at ?.Status 400 Bad Request should display with a Message Missing Items OR Invalid Entry.Check on &quot;Missing Field&quot; Names(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/PostMorbidity.feature:22)
</pre></div><a href='#' onClick='toggleBox("stack-trace2044852019", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2044852019'><pre>java.lang.AssertionError: expected [400] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at MorbidityAPI.PostMorbidityAPI.status_bad_request_should_display_with_a_message_missing_items_or_invalid_entry_check_on_names(PostMorbidityAPI.java:160)
	at ?.Status 400 Bad Request should display with a Message Missing Items OR Invalid Entry.Check on &quot;Missing Field&quot; Names(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/PostMorbidity.feature:22)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is able to create a new user record with either existing firstname or existing contact or existing email", "Optional[Validate and Test POST request for Users API]"</td>
<td><div><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: Successfully Created.
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:119)
	at ?.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:16)
</pre></div><a href='#' onClick='toggleBox("stack-trace2028922364", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2028922364'><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: Successfully Created.
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:119)
	at ?.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:16)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to add a existing record successfully", "Optional[Validate and Test Post Request for Morbidity API with authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [null] but found [5VA_5VB]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at org.testng.Assert.assertNull(Assert.java:953)
	at MorbidityAPI.PostMorbidityAPI.status_ok_should_display_with_a_message(PostMorbidityAPI.java:127)
	at ?.Status 200 Ok should display with a Message &quot;Error Occured&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/PostMorbidity.feature:16)
</pre></div><a href='#' onClick='toggleBox("stack-trace359873189", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace359873189'><pre>java.lang.AssertionError: expected [null] but found [5VA_5VB]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at org.testng.Assert.assertNull(Assert.java:953)
	at MorbidityAPI.PostMorbidityAPI.status_ok_should_display_with_a_message(PostMorbidityAPI.java:127)
	at ?.Status 200 Ok should display with a Message &quot;Error Occured&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/PostMorbidity.feature:16)
</pre></div></td>
<td>1</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Users By First Name When servers no running", "Optional[Validate and Test Get Request for UserAPI By First Name]"</td>
<td><div><pre>java.lang.IllegalArgumentException: basePath cannot be null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
	at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:54)
	at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.&lt;init&gt;(RequestSpecificationImpl.groovy:140)
	at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1453)
	at io.restassured.RestAssured.given(RestAssured.java:654)
	at stepdefinitions.GetUserFirstNameStepDefs.for_get_request_the_authorization_is_set_to_basic_auth_with_servers_not_running(GetUserFirstNameStepDefs.java:132)
	at ?.For Get request, the Authorization is set to Basic auth with servers not running(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetUsersAPIFeatures/GetUserFirstName.feature:41)
</pre></div><a href='#' onClick='toggleBox("stack-trace373562387", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace373562387'><pre>java.lang.IllegalArgumentException: basePath cannot be null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
	at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:54)
	at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.&lt;init&gt;(RequestSpecificationImpl.groovy:140)
	at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1453)
	at io.restassured.RestAssured.given(RestAssured.java:654)
	at stepdefinitions.GetUserFirstNameStepDefs.for_get_request_the_authorization_is_set_to_basic_auth_with_servers_not_running(GetUserFirstNameStepDefs.java:132)
	at ?.For Get request, the Authorization is set to Basic auth with servers not running(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetUsersAPIFeatures/GetUserFirstName.feature:41)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Vegetarian with invalid query", "Optional[Validate and Test Get Request for DieticianAPI with Vegetarian]"</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetVegetarianSteps.status_validation_error_will_be_shown(RecipeAPIGetVegetarianSteps.java:68)
	at ?.Status 400 Validation Error will be shown(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetVegetarian.feature:15)
</pre></div><a href='#' onClick='toggleBox("stack-trace1561206547", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1561206547'><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetVegetarianSteps.status_validation_error_will_be_shown(RecipeAPIGetVegetarianSteps.java:68)
	at ?.Status 400 Validation Error will be shown(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetVegetarian.feature:15)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able put (update) Morbidity records", "Optional[Verify Put Request for Morbidity API.]"</td>
<td><div><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidPutAPIStepDef.user_will_check_for(MorbidPutAPIStepDef.java:63)
	at ?.User will check for 404  &quot;autoTestMarkerRefN&quot;  &quot;autoTestTestUnituptN&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/PutMorbidityFeatures/PutMorbidityAPI.feature:21)
</pre></div><a href='#' onClick='toggleBox("stack-trace1553997313", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1553997313'><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidPutAPIStepDef.user_will_check_for(MorbidPutAPIStepDef.java:63)
	at ?.User will check for 404  &quot;autoTestMarkerRefN&quot;  &quot;autoTestTestUnituptN&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/PutMorbidityFeatures/PutMorbidityAPI.feature:21)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if user record gets deleted when dietician and user id are incorrect", "Optional[Validate DeleteUser Request for Dietician Users API]"</td>
<td><div><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at ?.Status 404 user not found should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:16)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div><a href='#' onClick='toggleBox("stack-trace323688878", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace323688878'><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at ?.Status 404 user not found should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:16)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeType with invalid query", "Optional[Validate and Test Get Request for DieticianAPI with RecipeType]"</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetRecipeTypeSteps.status_validation_error_will_be_displays(RecipeAPIGetRecipeTypeSteps.java:69)
	at ?.Status 400 Validation Error will be displays(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetRecipeType.feature:15)
</pre></div><a href='#' onClick='toggleBox("stack-trace60216880", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace60216880'><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetRecipeTypeSteps.status_validation_error_will_be_displays(RecipeAPIGetRecipeTypeSteps.java:69)
	at ?.Status 400 Validation Error will be displays(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetRecipeType.feature:15)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets Internal Server error.", "Optional[Verify Get Request for Morbidity API.]"</td>
<td><div><pre>java.lang.AssertionError: expected [500] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidAPIStepDef.user_will_check_for_ok(MorbidAPIStepDef.java:57)
	at ?.User will check for 500  Ok.(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetMorbidityFeatures/MorbidityAPI.feature:32)
</pre></div><a href='#' onClick='toggleBox("stack-trace1994473992", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1994473992'><pre>java.lang.AssertionError: expected [500] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidAPIStepDef.user_will_check_for_ok(MorbidAPIStepDef.java:57)
	at ?.User will check for 500  Ok.(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetMorbidityFeatures/MorbidityAPI.feature:32)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if user record gets deleted when dietician and user id are incorrect", "Optional[Validate DeleteUser Request for Dietician Users API]"</td>
<td><div><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at ?.Status 404 user not found should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:16)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div><a href='#' onClick='toggleBox("stack-trace444638058", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace444638058'><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at ?.Status 404 user not found should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:16)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.status_user_not_found_should_be_displayed(DeleteUser.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able put (update) Morbidity records", "Optional[Verify Put Request for Morbidity API.]"</td>
<td><div><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidPutAPIStepDef.user_will_check_for(MorbidPutAPIStepDef.java:63)
	at ?.User will check for 404  &quot;autoTestMarkerRefnoo&quot;  &quot;autoTestTestUnituptnoo&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/PutMorbidityFeatures/PutMorbidityAPI.feature:21)
</pre></div><a href='#' onClick='toggleBox("stack-trace547733262", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace547733262'><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidPutAPIStepDef.user_will_check_for(MorbidPutAPIStepDef.java:63)
	at ?.User will check for 404  &quot;autoTestMarkerRefnoo&quot;  &quot;autoTestTestUnituptnoo&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/PutMorbidityFeatures/PutMorbidityAPI.feature:21)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that existing user record is updated", "Optional[Validate Put User Request for Dietician Users API]"</td>
<td><div><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_code_record_updated_should_be_displayed(PutUsers.java:82)
	at ?.Status code 200 record updated should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:7)
</pre></div><a href='#' onClick='toggleBox("stack-trace114920439", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace114920439'><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_code_record_updated_should_be_displayed(PutUsers.java:82)
	at ?.Status code 200 record updated should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:7)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able put (update) Morbidity records", "Optional[Verify Put Request for Morbidity API.]"</td>
<td><div><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidPutAPIStepDef.user_will_check_for(MorbidPutAPIStepDef.java:63)
	at ?.User will check for 404  &quot;autoTestMarkerRefNo&quot;  &quot;autoTestTestUnitNo&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/PutMorbidityFeatures/PutMorbidityAPI.feature:21)
</pre></div><a href='#' onClick='toggleBox("stack-trace729060356", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace729060356'><pre>java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidPutAPIStepDef.user_will_check_for(MorbidPutAPIStepDef.java:63)
	at ?.User will check for 404  &quot;autoTestMarkerRefNo&quot;  &quot;autoTestTestUnitNo&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/PutMorbidityFeatures/PutMorbidityAPI.feature:21)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to delete record successfully", "Optional[Validate and Test Delete Request for Morbidity API with valid authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [Successfully Deleted.] but found [Already Deleted OR wrong MorbidityName ,MorbidityTestId.]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at MorbidityAPI.DeleteMorbidity.status_ok_is_displayed_with_morbidity_name_morbidity_test_id_and_message_as_is_displayed(DeleteMorbidity.java:51)
	at ?.Status 200 OK is displayed with Morbidity Name, MorbidityTestId and Message as &quot;Successfully Deleted.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:8)
</pre></div><a href='#' onClick='toggleBox("stack-trace328786858", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace328786858'><pre>java.lang.AssertionError: expected [Successfully Deleted.] but found [Already Deleted OR wrong MorbidityName ,MorbidityTestId.]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at MorbidityAPI.DeleteMorbidity.status_ok_is_displayed_with_morbidity_name_morbidity_test_id_and_message_as_is_displayed(DeleteMorbidity.java:51)
	at ?.Status 200 OK is displayed with Morbidity Name, MorbidityTestId and Message as &quot;Successfully Deleted.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:8)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if existing user record can be updated with null values or empty fields", "Optional[Validate Put User Request for Dietician Users API]"</td>
<td><div><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_code_bad_request_should_be_displayed(PutUsers.java:169)
	at ?.Status code 400 bad request should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:19)
</pre></div><a href='#' onClick='toggleBox("stack-trace1032607231", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1032607231'><pre>java.lang.NoSuchMethodError: &apos;void org.testng.Assert.assertEquals(java.lang.Integer, int)&apos;
	at stepdefinitions.PutUsers.status_code_bad_request_should_be_displayed(PutUsers.java:169)
	at ?.Status code 400 bad request should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/PutUsers.feature:19)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if user record gets deleted without authorization", "Optional[Validate DeleteUser Request for Dietician Users API]"</td>
<td><div><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.toJsonString(JsonPath.java:1064)
	at io.restassured.path.json.JsonPath.prettify(JsonPath.java:685)
	at io.restassured.path.json.JsonPath.prettyPrint(JsonPath.java:700)
	at stepdefinitions.DeleteUser.status_unauthorized_should_be_displayed(DeleteUser.java:92)
	at ?.Status 401 Unauthorized should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:27)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.toJsonString(JsonPath.java:1064)
	at io.restassured.path.json.JsonPath.prettify(JsonPath.java:685)
	at io.restassured.path.json.JsonPath.prettyPrint(JsonPath.java:700)
	at stepdefinitions.DeleteUser.status_unauthorized_should_be_displayed(DeleteUser.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div><a href='#' onClick='toggleBox("stack-trace1457809297", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1457809297'><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.toJsonString(JsonPath.java:1064)
	at io.restassured.path.json.JsonPath.prettify(JsonPath.java:685)
	at io.restassured.path.json.JsonPath.prettyPrint(JsonPath.java:700)
	at stepdefinitions.DeleteUser.status_unauthorized_should_be_displayed(DeleteUser.java:92)
	at ?.Status 401 Unauthorized should be displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:27)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.toJsonString(JsonPath.java:1064)
	at io.restassured.path.json.JsonPath.prettify(JsonPath.java:685)
	at io.restassured.path.json.JsonPath.prettyPrint(JsonPath.java:700)
	at stepdefinitions.DeleteUser.status_unauthorized_should_be_displayed(DeleteUser.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is able to create a new user record with missing mandatory field", "Optional[Validate and Test POST request for Users API]"</td>
<td><div><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: Missing Items OR Invalid Entry. Check on [&apos;Allergy&apos;]
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_missing_items_or_invalid_entry_check_on_fieldname(PostUsers.java:271)
	at ?.User should be displayed success status code 200 with message Missing Items OR Invalid Entry. Check on fieldname(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:28)
</pre></div><a href='#' onClick='toggleBox("stack-trace1774864575", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1774864575'><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: Missing Items OR Invalid Entry. Check on [&apos;Allergy&apos;]
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_missing_items_or_invalid_entry_check_on_fieldname(PostUsers.java:271)
	at ?.User should be displayed success status code 200 with message Missing Items OR Invalid Entry. Check on fieldname(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:28)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to delete record successfully with incorrect url", "Optional[Validate and Test Delete Request for Morbidity API with valid authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [405] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at MorbidityAPI.DeleteMorbidity.status_method_not_allowed_will_be_displayed_with_a_message(DeleteMorbidity.java:96)
	at ?.Status 405 Method Not Allowed will be displayed with a message &quot;The method is not allowed for the requested URL.&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:30)
</pre></div><a href='#' onClick='toggleBox("stack-trace1923082984", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1923082984'><pre>java.lang.AssertionError: expected [405] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at MorbidityAPI.DeleteMorbidity.status_method_not_allowed_will_be_displayed_with_a_message(DeleteMorbidity.java:96)
	at ?.Status 405 Method Not Allowed will be displayed with a message &quot;The method is not allowed for the requested URL.&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:30)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to delete record successfully", "Optional[Validate and Test Delete Request for Morbidity API with valid authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [Successfully Deleted.] but found [Already Deleted OR wrong MorbidityName ,MorbidityTestId.]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at MorbidityAPI.DeleteMorbidity.status_ok_is_displayed_with_morbidity_name_morbidity_test_id_and_message_as_is_displayed(DeleteMorbidity.java:51)
	at ?.Status 200 OK is displayed with Morbidity Name, MorbidityTestId and Message as &quot;Successfully Deleted.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:8)
</pre></div><a href='#' onClick='toggleBox("stack-trace1170570685", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1170570685'><pre>java.lang.AssertionError: expected [Successfully Deleted.] but found [Already Deleted OR wrong MorbidityName ,MorbidityTestId.]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at MorbidityAPI.DeleteMorbidity.status_ok_is_displayed_with_morbidity_name_morbidity_test_id_and_message_as_is_displayed(DeleteMorbidity.java:51)
	at ?.Status 200 OK is displayed with Morbidity Name, MorbidityTestId and Message as &quot;Successfully Deleted.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:8)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of with RecipeIngredient with invalid request query string", "Optional[Validate and Test Get Request for DieticianAPI with RecipeIngredient]"</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetRecipeIngredientSteps.status_validation_error_will_be_seen(RecipeAPIGetRecipeIngredientSteps.java:65)
	at ?.Status 400 Validation Error will be seen(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetIngredient.feature:15)
</pre></div><a href='#' onClick='toggleBox("stack-trace2030318015", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2030318015'><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetRecipeIngredientSteps.status_validation_error_will_be_seen(RecipeAPIGetRecipeIngredientSteps.java:65)
	at ?.Status 400 Validation Error will be seen(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetIngredient.feature:15)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeNutrient with invalid request query string", "Optional[Validate and Test Get Request for DieticianAPI with RecipeNutrient]"</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetNutrientSteps.status_validation_error(RecipeAPIGetNutrientSteps.java:66)
	at ?.Status 400 Validation Error(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetNutrient.feature:14)
</pre></div><a href='#' onClick='toggleBox("stack-trace2100400522", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2100400522'><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at RecipesAPI.RecipeAPIGetNutrientSteps.status_validation_error(RecipeAPIGetNutrientSteps.java:66)
	at ?.Status 400 Validation Error(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/RecipeAPIFeatures/RecipeAPIGetNutrient.feature:14)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is not able to create a new user record when UserType is other than Dietician/Patient", "Optional[Validate and Test POST request for Users API]"</td>
<td><div><pre>java.lang.AssertionError: 1 expectation failed.
Expected status code &lt;400&gt; but was &lt;200&gt;.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
	at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:136)
	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
	at stepdefinitions.PostUsers.user_should_be_displayed_validation_error_message_user_type_should_be_dietician_patient(PostUsers.java:339)
	at ?.User should be displayed 400 validation error message UserType should be Dietician/Patient(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:40)
</pre></div><a href='#' onClick='toggleBox("stack-trace1246551728", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1246551728'><pre>java.lang.AssertionError: 1 expectation failed.
Expected status code &lt;400&gt; but was &lt;200&gt;.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
	at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:136)
	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
	at stepdefinitions.PostUsers.user_should_be_displayed_validation_error_message_user_type_should_be_dietician_patient(PostUsers.java:339)
	at ?.User should be displayed 400 validation error message UserType should be Dietician/Patient(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:40)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to delete record successfully", "Optional[Validate and Test Delete Request for Morbidity API with valid authorization]"</td>
<td><div><pre>java.lang.AssertionError: expected [Successfully Deleted.] but found [Already Deleted OR wrong MorbidityName ,MorbidityTestId.]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at MorbidityAPI.DeleteMorbidity.status_ok_is_displayed_with_morbidity_name_morbidity_test_id_and_message_as_is_displayed(DeleteMorbidity.java:51)
	at ?.Status 200 OK is displayed with Morbidity Name, MorbidityTestId and Message as &quot;Successfully Deleted.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:8)
</pre></div><a href='#' onClick='toggleBox("stack-trace274234597", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace274234597'><pre>java.lang.AssertionError: expected [Successfully Deleted.] but found [Already Deleted OR wrong MorbidityName ,MorbidityTestId.]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at MorbidityAPI.DeleteMorbidity.status_ok_is_displayed_with_morbidity_name_morbidity_test_id_and_message_as_is_displayed(DeleteMorbidity.java:51)
	at ?.Status 200 OK is displayed with Morbidity Name, MorbidityTestId and Message as &quot;Successfully Deleted.&quot; is displayed(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/MorbidityFeatures/DeleteMorbidity.feature:8)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets Internal Server error.", "Optional[Verify Get Request for Morbidity ID API.]"</td>
<td><div><pre>java.lang.AssertionError: expected [500] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidAPI_MorbidityIdStepDef.user_checks_for_ok_and(MorbidAPI_MorbidityIdStepDef.java:53)
	at ?.User checks for 500  Ok and(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetMorbidityFeatures/Morbidity_MorbidityId.feature:34)
</pre></div><a href='#' onClick='toggleBox("stack-trace150619719", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace150619719'><pre>java.lang.AssertionError: expected [500] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at stepdefinitions.MorbidAPI_MorbidityIdStepDef.user_checks_for_ok_and(MorbidAPI_MorbidityIdStepDef.java:53)
	at ?.User checks for 500  Ok and(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/GetMorbidityFeatures/Morbidity_MorbidityId.feature:34)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user record gets deleted", "Optional[Validate DeleteUser Request for Dietician Users API]"</td>
<td><div><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.user_sends_delete_user_request_with_existing_dietician_and_user_id(DeleteUser.java:33)
	at ?.User sends delete user request with existing dietician and user id &quot;Users/DieticianId=DT002&amp;UserId=PT0006&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:6)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.user_sends_delete_user_request_with_existing_dietician_and_user_id(DeleteUser.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div><a href='#' onClick='toggleBox("stack-trace2050761537", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2050761537'><pre>io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.user_sends_delete_user_request_with_existing_dietician_and_user_id(DeleteUser.java:33)
	at ?.User sends delete user request with existing dietician and user id &quot;Users/DieticianId=DT002&amp;UserId=PT0006&quot;(file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/DeleteUser.feature:6)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading &apos;&lt;&apos;, no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at stepdefinitions.DeleteUser.user_sends_delete_user_request_with_existing_dietician_and_user_id(DeleteUser.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:146)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:146)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is unable to create a new user record with existing firstname, contact and email", "Optional[Validate and Test POST request for Users API]"</td>
<td><div><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: User detail already Exists. Check on [ Firstname, Contact , Email ]
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_user_detail_already_exists_check_on_firstname_contact_email(PostUsers.java:218)
	at ?.User should be displayed success status code 200 with message User detail already Exists. Check on [ Firstname, Contact , Email ](file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:22)
</pre></div><a href='#' onClick='toggleBox("stack-trace2130300932", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2130300932'><pre>java.lang.AssertionError: 1 expectation failed.
JSON path Message doesn&apos;t match.
Expected: User detail already Exists. Check on [ Firstname, Contact , Email ]
  Actual: Missing Items OR Invalid Entry.Check on [&apos;Extra attributes mentioned.&apos;]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:263)
	at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:110)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_user_detail_already_exists_check_on_firstname_contact_email(PostUsers.java:218)
	at ?.User should be displayed success status code 200 with message User detail already Exists. Check on [ Firstname, Contact , Email ](file:///C:/Users/geeta/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:22)
</pre></div></td>
<td>1</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we are getting records of Users By Dietician ID with Valid DieticianID", "Optional[Validate and Test Get Request for UserAPI By Dietician Id]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeNutrient with Unauthorised Access", "Optional[Validate and Test Get Request for DieticianAPI with RecipeNutrient]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By DieticianID with Invalid DieticianID", "Optional[Validate and Test Get Request for UserAPI By Dietician Id]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating negative Scenario if we are getting record of Users By Email With Invalid EndPoint", "Optional[Validating and Testing Get Request for UserAPI By EmailId]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By DieticianID with Invalid DieticianID", "Optional[Validate and Test Get Request for UserAPI By Dietician Id]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By First Name with Invalid First Name", "Optional[Validate and Test Get Request for UserAPI By First Name]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of with RecipeNutrient", "Optional[Validate and Test Get Request for DieticianAPI with RecipeNutrient]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get records of User Type when server is down", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able get all Morbidity records with given Name.", "Optional[Verify Get Request for Morbidity Name API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able get all Morbidity records with given id.", "Optional[Verify Get Request for Morbidity ID API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets UnAuthorized Access.", "Optional[Verify Get Request for Morbidity API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that we are getting records of User by User Type", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By Contact with Invalid ContactNo", "Optional[Validate and Test Get Request for UserAPI By Contact]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets UnAuthorized Access.", "Optional[Verify Get Request for Morbidity ID API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is able to create a new user record with empty request body", "Optional[Validate and Test POST request for Users API]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Vegetarian", "Optional[Validate and Test Get Request for DieticianAPI with Vegetarian]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to add a new record successfully with out request body data", "Optional[Validate and Test Post Request for Morbidity API with authorization]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if We are getting all the records", "Optional[Validate and Test Get Request for DieticianAPI with no parameters]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of with RecipeType", "Optional[Validate and Test Get Request for DieticianAPI with RecipeType]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Non-Vegetarian with Unauthorised Access", "Optional[Validate and Test Get Request for DieticianAPI with Non-Vegetarian]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "User is able to get list of all users", "Optional[Validate and Test GET request for Users API]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able get All Morbidity records.", "Optional[Validate and Test Get Request for Morbidity API with valid authorization]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeNutrient with invalid endpoint", "Optional[Validate and Test Get Request for DieticianAPI with RecipeIngredient]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating negative Scenario if we are getting record of Users By DieticianID With Invalid EndPoint", "Optional[Validate and Test Get Request for UserAPI By Dietician Id]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if user is able to add a new record successfully", "Optional[Validate and Test Post Request for Morbidity API with authorization]"</td>
<td></td>
<td>5</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets Not Found error(invalid url).", "Optional[Verify Get Request for Morbidity API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get user records in case of invalid User Type", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able get All Morbidity records.", "Optional[Verify Get Request for Morbidity API.]"</td>
<td></td>
<td>6</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeType with Unauthorised Acces", "Optional[Validate and Test Get Request for DieticianAPI with RecipeType]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of with RecipeIngredient", "Optional[Validate and Test Get Request for DieticianAPI with RecipeIngredient]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we are getting records of Users By Email with Valid Email Id", "Optional[Validating and Testing Get Request for UserAPI By EmailId]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By First Name with Invalid First Name", "Optional[Validate and Test Get Request for UserAPI By First Name]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to delete record successfully with invalid credentials", "Optional[Validate and Test Delete Request for Morbidity API with valid authorization]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get user records in case of invalid User Type", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets Not Found error(invalid endpoints).", "Optional[Verify Get Request for Morbidity Name API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we are getting records of Users By First Name with Valid First Name", "Optional[Validate and Test Get Request for UserAPI By First Name]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able put (update) Morbidity records.", "Optional[Verify Put Request for Morbidity API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if user is able to add a new record successfully with invalid authorization", "Optional[Validate and Test Post Request for Morbidity API with authorization]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Non-Vegetarian with invalid endpoint", "Optional[Validate and Test Get Request for DieticianAPI with Non-Vegetarian]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we are getting records of User Type with no authorization", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By Email with Invalid EmailId", "Optional[Validating and Testing Get Request for UserAPI By EmailId]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeNutrient with invalid endpoint", "Optional[Validate and Test Get Request for DieticianAPI with RecipeNutrient]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Vegetarian with default authorization", "Optional[Validate and Test Get Request for DieticianAPI with Vegetarian]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Vegetarian with invalid endpoint", "Optional[Validate and Test Get Request for DieticianAPI with Vegetarian]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets UnAuthorized Access.", "Optional[Verify Get Request for Morbidity Name API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating negative Scenario if we are getting record of Users By ContactNo With Invalid EndPoint", "Optional[Validate and Test Get Request for UserAPI By Contact]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we are getting records of Users By Contact with Valid ContactNo", "Optional[Validate and Test Get Request for UserAPI By Contact]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By Email with Invalid EmailId", "Optional[Validating and Testing Get Request for UserAPI By EmailId]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating Negative case if we are getting record of Users By First Name With Invalid Authorisation", "Optional[Validate and Test Get Request for UserAPI By First Name]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get user records in case of invalid User Type", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeType with invalid endpoint", "Optional[Validate and Test Get Request for DieticianAPI with RecipeType]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get user records in case of invalid User Type", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get user records in case of invalid User Type", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of RecipeIngredient with Unauthorised Acces", "Optional[Validate and Test Get Request for DieticianAPI with RecipeIngredient]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating if we are getting record of Users By Contact with Invalid ContactNo", "Optional[Validate and Test Get Request for UserAPI By Contact]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user gets Not Found error(invalid endpoints).", "Optional[Verify Get Request for Morbidity ID API.]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Validating negative Scenario if we are getting record of Users By First Name With Invalid EndPoint", "Optional[Validate and Test Get Request for UserAPI By First Name]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify if we can get records of User Type when server is down", "Optional[Validate Get User Request for Dietician Users API for User Type - Patient / Dietician]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
<tr>
<td title='runner.MasterTestRunner.runScenario()'><b>runScenario</b><br>Test class: runner.MasterTestRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Checking if we are getting record of Non-Vegetarian with valid", "Optional[Validate and Test Get Request for DieticianAPI with Non-Vegetarian]"</td>
<td></td>
<td>0</td>
<td>runner.MasterTestRunner@43effd89</td></tr>
</table><p>
</body>
</html>