<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PRQP1M3" failures="1" tests="18" name="TestRunner.MyTestRunner" time="4.461" errors="3" timestamp="2022-07-20T11:49:42 EDT" skipped="0">
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.030"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.027"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.017"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.018"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.022"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.020"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.031"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.039">
    <error message="Cannot invoke &quot;io.restassured.response.Response.then()&quot; because &quot;this.postUsersResponse&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.then()" because "this.postUsersResponse" is null
at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:98)
at ✽.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/star/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:28)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.046">
    <error message="Cannot invoke &quot;io.restassured.response.Response.then()&quot; because &quot;this.postUsersResponse&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.then()" because "this.postUsersResponse" is null
at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:98)
at ✽.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/star/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:16)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.073">
    <error message="Cannot invoke &quot;io.restassured.response.Response.then()&quot; because &quot;this.postUsersResponse&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.then()" because "this.postUsersResponse" is null
at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:98)
at ✽.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/star/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:22)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.035"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.026"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.020"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.018"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="3.959">
    <failure message="1 expectation failed.
Expected status code &lt;200&gt; but was &lt;308&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <308>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:505)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:687)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:136)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at stepdefinitions.PostUsers.user_should_be_displayed_success_status_code_with_message_successfully_created_with_automatically_generated_userid(PostUsers.java:98)
at ✽.User should be displayed success status code 200 with message Successfully Created. with automatically generated userid(file:///C:/Users/star/git/DieticianAPI-Hackathon/src/test/resources/features/Users/POSTUsers.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.021"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.041"/>
  <system-out/>
  <testcase classname="TestRunner.MyTestRunner" name="runScenario" time="0.018"/>
  <system-out/>
</testsuite> <!-- TestRunner.MyTestRunner -->
